language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
  global:
    - PACKAGE=records
    - DISTRO=debian-stable
    - OPAM_VERSION=1.2.2
  matrix:
    - OCAML_VERSION=4.02.3
    - OCAML_VERSION=4.03.0
    - OCAML_VERSION=4.04.0
    - OCAML_VERSION=4.05.0
    - OCAML_VERSION=4.06.0
